import 'ble_pattern_analyzer.dart';
import 'smart_device_classifier.dart';

/// Professional device profile code generator
/// Creates production-ready parsing code from captured data
class ProfileGeneratorService {
  /// Generate complete device profile code
  static String generateProfile({
    required String profileKey,
    required String displayName,
    required DeviceClassification classification,
    required String serviceUuid,
    required String? dataCharUuid,
    required List<ParseSuggestion> parseSuggestions,
    required String unit,
  }) {
    final manufacturer = _guessManufacturerEnum(classification.manufacturer);
    final deviceType = _guessDeviceTypeEnum(classification.category);
    final connectionType = classification.connectionType;
    
    // Select best parse suggestion
    final bestParse = parseSuggestions.isNotEmpty ? parseSuggestions.first : null;
    
    final code = StringBuffer();
    
    code.writeln('// ============================================================================');
    code.writeln('// $displayName');
    code.writeln('// Auto-generated by BLE Sniffer on ${DateTime.now().toString().split('.').first}');
    code.writeln('// Classification: ${classification.categoryDisplay}');
    code.writeln('// Confidence: ${classification.confidence.toStringAsFixed(1)}%');
    code.writeln('// Connection: $connectionType');
    code.writeln('// ============================================================================');
    code.writeln();
    
    // Device Profile
    code.writeln("'$profileKey': DeviceProfile(");
    code.writeln("  name: '$displayName',");
    code.writeln("  manufacturer: HvacManufacturer.$manufacturer,");
    code.writeln("  type: HvacDeviceType.$deviceType,");
    
    if (connectionType == 'Broadcast-Only') {
      code.writeln("  serviceUuids: [], // Broadcast-only device");
      code.writeln("  isBroadcastOnly: true,");
      code.writeln("  manufacturerId: 0x5046, // TODO: Update with actual manufacturer ID");
    } else {
      code.writeln("  serviceUuids: ['$serviceUuid'],");
      if (dataCharUuid != null) {
        code.writeln("  dataCharacteristicUuid: '$dataCharUuid',");
      }
    }
    
    code.writeln("  unit: '$unit',");
    code.writeln("  parseReading: _parse${_toPascalCase(profileKey)},");
    code.writeln('),');
    code.writeln();
    
    // Parsing function
    if (bestParse != null) {
      code.writeln('/// Parse $displayName reading from raw BLE data');
      code.writeln('/// Auto-detected format: ${bestParse.formatName}');
      code.writeln('/// Position: bytes ${bestParse.offset}-${bestParse.offset + bestParse.length - 1}');
      code.writeln('/// Confidence: ${(bestParse.confidence * 100).toStringAsFixed(1)}%');
      code.writeln('/// Detected as: ${bestParse.categoryDisplay}');
      code.writeln(bestParse.generateDartCode('_parse${_toPascalCase(profileKey)}'));
    } else {
      code.writeln('/// Parse $displayName reading from raw BLE data');
      code.writeln('/// TODO: Implement parsing logic based on captured data');
      code.writeln('double _parse${_toPascalCase(profileKey)}(List<int> rawData) {');
      code.writeln('  if (rawData.length < 2) return double.nan;');
      code.writeln('  ');
      code.writeln('  final bytes = Uint8List.fromList(rawData);');
      code.writeln('  final byteData = ByteData.view(bytes.buffer);');
      code.writeln('  ');
      code.writeln('  try {');
      code.writeln('    // TODO: Adjust based on actual data format');
      code.writeln('    final rawValue = byteData.getInt16(0, Endian.little);');
      code.writeln('    return rawValue / 10.0; // Adjust divisor as needed');
      code.writeln('  } catch (e) {');
      code.writeln('    return double.nan;');
      code.writeln('  }');
      code.writeln('}');
    }
    
    return code.toString();
  }

  /// Generate profile with alternative suggestions
  static String generateProfileWithAlternatives({
    required String profileKey,
    required String displayName,
    required DeviceClassification classification,
    required String serviceUuid,
    required String? dataCharUuid,
    required List<ParseSuggestion> parseSuggestions,
    required String unit,
  }) {
    final mainCode = generateProfile(
      profileKey: profileKey,
      displayName: displayName,
      classification: classification,
      serviceUuid: serviceUuid,
      dataCharUuid: dataCharUuid,
      parseSuggestions: parseSuggestions,
      unit: unit,
    );
    
    if (parseSuggestions.length <= 1) {
      return mainCode;
    }
    
    final code = StringBuffer(mainCode);
    
    code.writeln();
    code.writeln('// Alternative parsing methods (if primary doesn\'t work):');
    code.writeln('// Test these alternatives against your captured data');
    code.writeln();
    
    for (int i = 1; i < parseSuggestions.length && i < 4; i++) {
      final alt = parseSuggestions[i];
      code.writeln('// Alternative $i: ${alt.humanReadable}');
      code.writeln('// Confidence: ${(alt.confidence * 100).toStringAsFixed(1)}%');
      code.writeln('// Detected as: ${alt.categoryDisplay}');
      code.writeln('/*');
      code.writeln(alt.generateDartCode('_parse${_toPascalCase(profileKey)}_alt$i'));
      code.writeln('*/');
      code.writeln();
    }
    
    return code.toString();
  }

  /// Generate comprehensive integration guide
  static String generateIntegrationGuide({
    required String displayName,
    required DeviceClassification classification,
    required String profileKey,
    required String serviceUuid,
    required String? dataCharUuid,
    List<ParseSuggestion>? parseSuggestions,
    Map<String, dynamic>? captureMetadata,
  }) {
    final guide = StringBuffer();
    
    guide.writeln('# Integration Guide: $displayName');
    guide.writeln();
    guide.writeln('**Auto-generated:** ${DateTime.now().toString().split('.').first}');
    guide.writeln();
    
    guide.writeln('## Device Information');
    guide.writeln();
    guide.writeln('- **Profile Key:** `$profileKey`');
    guide.writeln('- **Display Name:** $displayName');
    guide.writeln('- **Manufacturer:** ${classification.manufacturer ?? 'Unknown'}');
    guide.writeln('- **Device Type:** ${classification.categoryDisplay}');
    guide.writeln('- **Connection Type:** ${classification.connectionType}');
    guide.writeln('- **Confidence:** ${classification.confidence.toStringAsFixed(1)}% (${classification.confidenceDisplay})');
    guide.writeln();
    
    if (classification.connectionType != 'Broadcast-Only') {
      guide.writeln('## BLE Protocol');
      guide.writeln();
      guide.writeln('- **Service UUID:** `$serviceUuid`');
      if (dataCharUuid != null) {
        guide.writeln('- **Data Characteristic:** `$dataCharUuid`');
      }
      guide.writeln();
    }
    
    if (parseSuggestions != null && parseSuggestions.isNotEmpty) {
      guide.writeln('## Data Format Analysis');
      guide.writeln();
      guide.writeln('Top ${parseSuggestions.length.clamp(1, 3)} suggested parsing methods:');
      guide.writeln();
      
      for (int i = 0; i < parseSuggestions.length && i < 3; i++) {
        final suggestion = parseSuggestions[i];
        guide.writeln('### ${i + 1}. ${suggestion.humanReadable}');
        guide.writeln();
        guide.writeln('- **Format:** ${suggestion.formatName}');
        guide.writeln('- **Category:** ${suggestion.categoryDisplay}');
        guide.writeln('- **Confidence:** ${(suggestion.confidence * 100).toStringAsFixed(1)}%');
        guide.writeln('- **Sample Value:** ${suggestion.value.toStringAsFixed(2)}');
        if (suggestion.sampleCount > 1) {
          guide.writeln('- **Sample Count:** ${suggestion.sampleCount} packets');
        }
        guide.writeln();
      }
    }
    
    guide.writeln('## Integration Steps');
    guide.writeln();
    guide.writeln('1. **Add Profile to `device_registry.dart`:**');
    guide.writeln('   - Copy the generated profile code into the `_profiles` map');
    guide.writeln('   - Add the parsing function to the file');
    guide.writeln();
    guide.writeln('2. **Test Connection:**');
    guide.writeln('   - Use BLE Sniffer to verify data is parsed correctly');
    guide.writeln('   - Compare parsed values with manufacturer\'s app');
    guide.writeln();
    guide.writeln('3. **Add to UI:**');
    guide.writeln('   - Device will auto-appear in Tools Hub after profile added');
    guide.writeln('   - Readings will display automatically');
    guide.writeln();
    guide.writeln('4. **Validate:**');
    guide.writeln('   - Test with real device');
    guide.writeln('   - Verify readings match expected values');
    guide.writeln('   - Check edge cases (min/max values, negative numbers)');
    guide.writeln();
    
    if (classification.confidence < 70) {
      guide.writeln('## ⚠️ Low Confidence Warning');
      guide.writeln();
      guide.writeln('This device classification has a confidence of ${classification.confidence.toStringAsFixed(1)}%.');
      guide.writeln('Please carefully validate the generated code against actual device behavior.');
      guide.writeln('Consider capturing more data samples for better analysis.');
      guide.writeln();
    }
    
    guide.writeln('## Troubleshooting');
    guide.writeln();
    guide.writeln('If readings are incorrect:');
    guide.writeln();
    guide.writeln('1. **Check byte offset:** Data may start at a different position');
    guide.writeln('2. **Try alternative parsing methods:** See alternative suggestions in generated code');
    guide.writeln('3. **Verify endianness:** Try switching between little-endian and big-endian');
    guide.writeln('4. **Adjust scaling factor:** Try different divisors (÷1, ÷10, ÷100, ÷1000)');
    guide.writeln('5. **Check for headers:** Some devices have packet headers before data');
    guide.writeln('6. **Re-capture data:** Ensure you captured actual measurement changes');
    guide.writeln();
    
    return guide.toString();
  }

  /// Guess manufacturer enum from name
  static String _guessManufacturerEnum(String? manufacturer) {
    if (manufacturer == null) return 'unknown';
    
    final lower = manufacturer.toLowerCase();
    if (lower.contains('testo')) return 'testo';
    if (lower.contains('fieldpiece')) return 'fieldpiece';
    if (lower.contains('wey-tek') || lower.contains('weytek') || lower.contains('inficon')) {
      return 'weytek';
    }
    if (lower.contains('cps') || lower.contains('aab')) return 'ccs';
    if (lower.contains('weatherflow')) return 'weatherflow';
    if (lower.contains('yellow jacket')) return 'yellowJacket';
    if (lower.contains('parker')) return 'parker';
    
    return 'unknown';
  }

  /// Guess device type enum from category
  static String _guessDeviceTypeEnum(String category) {
    switch (category) {
      case 'temperature_probe':
        return 'temperatureProbe';
      case 'pressure_probe':
        return 'pressureProbe';
      case 'refrigerant_scale':
        return 'refrigerantScale';
      case 'airflow_meter':
        return 'airflowMeter';
      case 'clamp_meter':
        return 'clampMeter';
      case 'vacuum_gauge':
        return 'vacuumGauge';
      case 'manifold_gauge':
        return 'refrigerantGauge';
      default:
        return 'unknown';
    }
  }

  /// Convert snake_case to PascalCase
  static String _toPascalCase(String input) {
    return input
        .split('_')
        .map((word) => word.isEmpty
            ? ''
            : '${word[0].toUpperCase()}${word.substring(1).toLowerCase()}')
        .join('');
  }
}
