#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/usr/local/Caskroom/flutter/3.29.3/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/joeykeilbarth/Documents/hvac_support_app"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/joeykeilbarth/Documents/hvac_support_app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "FLUTTER_CLI_BUILD_MODE=debug"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzMuMC0xLjAucHJlLjgzMg==,RkxVVFRFUl9DSEFOTkVMPW1hc3Rlcg==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049ZDM1YmRlNTM2Mw==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049ZDM1YmRlNTM2Mw==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My45LjAgKGJ1aWxkIDMuOS4wLTI5My4wLmRldik="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/joeykeilbarth/Documents/hvac_support_app/.dart_tool/package_config.json"
